import type { Metadata } from "next";
import NavBar from "@/components/shared/NavBar";

export const metadata: Metadata = {
    title: "Category",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <div className="fixed top-0 right-0 left-0 w-full">
                <NavBar></NavBar>
            </div>
            <div className="pt-[200px]">
                {children}
            </div>
        </div>
    );
}
